### ISSUE TITLE
Document the use of `wait` in `tableCreate` and `dbCreate`

### ISSUE THREAD

**Issue by mglukhovsky** [rethinkdb/docs#1001]
@nanodeath suggested [on Twitter](https://twitter.com/nanodeath/status/689691463890767873) that it would be good to mention `wait()` on the docs for `tableCreate()`, since that's the most likely place you'll use it.

I think adding a mention to `dbCreate()` would also be a good thing.

**Comment by VeXocide** [comment]
Great idea, it might also be worth mentioning `wait(wait_for="all_replicas_ready")` in `reconfigure` and `rebalance`.

**Comment by danielmewes** [comment]
I don't think that `wait` is particularly useful in the context of `tableCreate`, since `tableCreate` already waits. Or is there an important use case that I'm missing?

I think it makes a lot of sense to mention next to `reconfigure` and `rebalanace` though, since those commands do *not* wait until the reconfiguration is complete.

Similarly we should mention `indexWait` in the `indexCreate` docs, if we're not doing so already.

**Comment by nanodeath** [comment]
You could document that `tableCreate` already `wait`s, perhaps? As a user, just because a command is successful doesn't necessarily mean that all the required operations have finished propagating.

**Comment by danielmewes** [comment]
@nanodeath That makes sense. Good idea.
