### ISSUE TITLE
Fold term

### ISSUE THREAD

**Issue by nighelles** [rethinkdb/docs#1008]
https://github.com/rethinkdb/rethinkdb/issues/3736

Syntax and behavior evolve throughout the issue, only thing that doesn't seem to be explained well is that the emit function returns an array, and all the arrays get appended together.

**Comment by chipotle** [comment]
I'd like to ping for a few examples of `fold` in practice. The examples in rethinkdb/rethinkdb#3736 are good, but they're all for the `concatMap` style with the emitting function -- there's no examples of just using `sequence.fold(base, function)` to get a value. And we definitely need at least one example for both forms that draws its sequence from a table rather than a ReQL expression. (The "return every third row" example does that, although it still feels a little contrived.)

**Comment by danielmewes** [comment]
@chipotle A typical example for the reduce-style variant is concatenating strings from an array or stream.

Example 1: Undoing a `split('')` (i.e. reassembling individual characters back into a string):
```js
var characters = r.expr("Hello world!").split("");
characters.fold("", function(acc, char) { return acc.add(char); } ).run(conn);
// Returns: "Hello world!"
```

Example 2: Concatenate words from a word array, inserting commas and spaces in between:
```js
var words = r.expr(["list", "of", "words"]);
words.fold("", function(acc, word) {
    return acc.add(r.branch(acc.eq(""), "", ", ")).add(word);
  }).run(conn);
// Returns: "list, of, words"
```

These example would theoretically have worked with `reduce` as well, since `reduce` happens to be sorted when applied to arrays. However this was not guaranteed, and just an implementation detail. With `fold` this is now guaranteed to work. Furthermore, this even works on streams rather than arrays with `fold` (in contrast to `reduce`). I can't come up with any great examples for the reduce-style variant that involve streams right now.

**Comment by nighelles** [comment]
You could get, say, the maximum N elements of a stream.
