### ISSUE TITLE
Also mention per-table memory overhead in "Understanding RethinkDB memory requirements"

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/docs#1010]
Originally opened this in https://github.com/rethinkdb/rethinkdb/issues/5229 by accident:
> We currently mention the overhead of 8 MB per table in http://rethinkdb.com/limitations/.
> 
> We should also mention it in http://rethinkdb.com/docs/memory-usage/

**Comment by chipotle** [comment]
I presume the 8 MB overhead is part of the "internal metadata" the memory usage documentation talks about. But is it that the metadata for blocks in RethinkDB will always take up a minimum of 8 MB overhead per table, or is it 8 MB of overhead in _addition_ to the 28 bytes per block? (And is that 28 bytes per block still correct, since it says "as of RethinkDB 1.13"?)

**Comment by danielmewes** [comment]
The 8 MB are in addition to the 28 bytes per block.

We actually did reduce the per-block overhead in 2.2. Good you asked.
However the reduction doesn't apply evenly to all types of blocks. While many blocks now only use 10 bytes, the conservative estimate is still close to 28 bytes per block. It very slightly decreased to 26 bytes.

We should probably just say 10-26 bytes per block.

**Comment by fluxxu** [comment]
@danielmewes 
I just found out on my PC; 600+ ready tables only use 2.2GB of memory. So it's about 4MB/table. (Windows 10 + rethinkdb 2.3.5-windows (MSC 190023506)
This is a huge improvement, and the documentation does not mention it.
THANK YOU!
