### ISSUE TITLE
Swap Detection

### ISSUE THREAD

**Issue by nighelles** [rethinkdb/docs#1023]
On OSX and Linux, there will be an issue created if swap is used.
On Linux it's only if our process uses swap, on OSX it's if the system uses swap.

https://github.com/rethinkdb/rethinkdb/issues/5235

**Comment by danielmewes** [comment]
One thing (and possibly the main thing) that will need updating is http://rethinkdb.com/docs/system-issues/

**Comment by danielmewes** [comment]
Example issue document:
```js
{
    "critical": false ,
    "description": "The following server encountered a memory problem: the_shadow_local_j4s. 

     The message reported is: Data from a process on this server has been placed into swap memory in the past hour. If the data is from RethinkDB, this may impact performance.

    " ,
    "id": "0755df1a-1a62-5b60-88bb-dd8a10c6f87f" ,
    "info": {
        "message": "Data from a process on this server has been placed into swap memory in the past hour. If the data is from RethinkDB, this may impact performance." ,
        "servers": [
            "the_shadow_local_j4s"
        ]
    } ,
    "type": "memory_error"
}
```

**Comment by coffenbacher** [comment]
Is there a way to disable this warning? We're intentionally using swap on SSD for our workload. Unless I'm misunderstanding the performance impact, and no swap (with no additional RAM) would be better than some swap? 

Obviously trading RAM for swap would be ideal, but we're (1) performing fine already and it's (2) cost-prohibitive for us to scale the RAM on this node.

**Comment by danielmewes** [comment]
@coffenbacher There is not currently. RethinkDB can be quite sensitive once parts of it are put into swap, so the warning is usually warranted. For example disconnects due to heartbeat timeouts are extremely common once parts of the rethinkdb process end up in swap.

Could you reduce the RethinkDB cache size to below the default minimum value of 100 MB to maybe reduce the likelihood that it has to go into swap? This would probably give you a better performance trade-off.

Regardless of whether there might be a way to reduce the usage of swap in your use case or not, is this issue getting in your way?

**Comment by coffenbacher** [comment]
Okay! Great to know. We will adjust our cache size to keep it out of swap - mistaken assumption on my part that some swap is better than no swap.

Either way, the warning wasn't an issue other than being persistently glaring in the UI. It seems it's warranted anyways, so this is correct behavior. Thanks for the help.
