### ISSUE TITLE
Node example missing sidebar

### ISSUE THREAD

**Issue by dalanmiller** [rethinkdb/docs#1043]
https://rethinkdb.com/docs/examples/node-todo-promises/

**Comment by chipotle** [comment]
This is not in the [example projects](https://rethinkdb.com/docs/examples/) page anymore, and as far as I remember the `examples` directory is actually deprecated. I suspect the issue here isn't that this example is missing the sidebar as much as that this example shouldn't still be linked anywhere.

**Comment by chipotle** [comment]
Closing in favor of #1050
