### ISSUE TITLE
Document 2.3 driver protocol handshake

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/docs#1058]
RethinkDB 2.3 will come with a new driver protocol handshake. So the "Perform a handshake" section of http://rethinkdb.com/docs/writing-drivers/ will need to be updated.

The new protocol handshake is described here: https://github.com/rethinkdb/rethinkdb/issues/5406#issuecomment-185980303 , though the actual magic number is going to be `0x34c2bdc3` in step 1.

The details of the authentication are missing in the spec from the issue.
@VeXocide could you describe the missing parts here please?

There is a "simplified" path through the handshake steps, which you get from going sequentially through the steps 1 to 7. Specifically you can ignore the note "Client proceeds to step 3 to reduce latency." in step 1, and instead wait for the response the server sends in step 2. This allows the client to go immediately to step 5, and then back to step 3. In this case, step 5 will only be entered once.
This is probably easier to explain in person, so @chipotle please let me know when you want to take a look at this.

I think we should explain that simplified protocol path, and then provide the details of the optimized one as an optional optimization (it reduces latency because the client doesn't have to wait on the server response from step 2).

**Comment by danielmewes** [comment]
. @mlucy pointed out that our actual implementation has a few differences to what is described in https://github.com/rethinkdb/rethinkdb/issues/5406#issuecomment-185980303 when it comes to how the authentication data is encoded. He also pointed out that we should probably document the format of the `nonce` we are using (16 random bytes base64 encoded).

@chipotle I recommend waiting for @VeXocide to fill in the details of the actual protocol on this one.

**Comment by VeXocide** [comment]
Given how https://github.com/rethinkdb/rethinkdb/issues/5406 has grown I'll write out the current implementation of the protocol.

We have a new magic version `V1_0` that's defined as `0x34c2bdc3`, it's sent by the connecting client to the server. Note that we still fully support the older `V0_4` protocol as well.

1: C --> S
`0x34c2bdc3`

The server then responds with a JSON blob followed by a null byte. This JSON contains an indication of success, the minimum and maximum protocol versions, and the server version. The minimum and maximum protocol versions are currently both `0`, we hope to add features in the future without changing the protocol significantly.

2: S --> C
```
{
    "success": true,
    "min_protocol_version": 0,
    "max_protocol_version": 0,
    "server_version": "2.3.0"
}
```

If an unknown magic version is sent the following null terminate string is sent back in response, note that we're not sending JSON here because we really don't know what the client expects, there's not much to go on.

2: S --> C on error
`ERROR: Received an unsupported protocol version. This port is for RethinkDB queries. Does your client driver version not match the server?`

The client then chooses the protocol version, authentication method, and starts authentication. We currently only support the `"SCRAM-SHA-256"` `"authentication_method"`, and the actual content of `"authentication"` is specified by https://tools.ietf.org/html/rfc7677. It might be worth noting here that RFC 7677 is derived from RFC 5802 with the hashing algorithm specified to be SHA-256, https://tools.ietf.org/html/rfc5802. This RFC is followed with the exception of error reporting, we use our upper level of reporting errors instead of the `e=` field as specified by the RFC. Secondly we do not support channel binding, and the client should not request this, as indicated by the first `"n"` in `"authentication"`.

3: C --> S
```
{
    "protocol_version": 0,
    "authentication_method": "SCRAM-SHA-256",
    "authentication": "n,,n=user,r=rOprNGfwEbeRWgbNEkqO"
}
```

The server then responds with the first server message in `"authentication"`.

4: S --> C
```
{
    "success": true,
    "authentication": "r=rOprNGfwEbeRWgbNEkqO%hvYDpWUa2RaTCAfuxFIlj)hNlF$k0,
      s=W22ZaJ0SNY7soEsUEjb6gQ==,i=4096"
}
```

On error the server will respond with the following null terminated JSON blob. Note that `10 <= "error_code" <= 20` are related to authentication, a ReqlAuthError should be thrown in these cases.

4: S --> C on error
```
{
    "success": false,
    "error": "You mucked up.",
    "error_code": 12
}
```

This continues for another back and forth as specified by the RFC, reporting errors as before.

5: C --> S
```
{
    "authentication": "c=biws,r=rOprNGfwEbeRWgbNEkqO%hvYDpWUa2RaTCAfuxFIlj)hNlF$k0,
      p=dHzbZapWIk4jUhN+Ute9ytag9zjfMHgsqmmiz7AndVQ="
}
```

6: S --> C
```
{
    "success": true,
    "authentication": "v=6rriTRBi23WpRR/wtup+mMhUZUn/dB5nLTJRsjl95G4="
}
```

At this point the user is logged in and can resume using the JSON query protocol as before.

**Comment by VeXocide** [comment]
There is a small optimization possible, the client may send messages 1 and 3 immediately without waiting for the server to respond, and may then read 2 and 4 afterwards handling them as usual. This should combine those in a single packet saving a TCP roundtrip.
