### ISSUE TITLE
Typo on 'Permissions and accounts'

### ISSUE THREAD

**Issue by mglukhovsky** [rethinkdb/docs#1085]
There are a few stray `&rarr;` HTML entities that aren't properly escaped in "The grant command".

![screen shot 2016-04-14 at 7 09 40 am](https://cloud.githubusercontent.com/assets/91193/14530946/1c9f3574-0210-11e6-9c88-415ec2776e9a.png)

**Comment by NeilHanlon** [comment]
It appears this is because it's in a code block so it's treating it literally. Perhaps a table is a better option?

**Comment by chipotle** [comment]
Yep, that's the problem -- we have a custom `{% apibody %}` Jekyll tag we use in the API pages that _does_ handle HTML entities, but that block isn't styled correctly when I use it here. I'll just stick to the code block but use the actual Unicode character "→" there. (It's not the first place in the docs there's a Unicode character rather than an entity code, so there's precedence...)
