### ISSUE TITLE
Add docs for rethinkdb proxy

### ISSUE THREAD

**Issue by jdoliner** [rethinkdb/docs#11]
We don't have any docs for rethinkdb proxy and it's actually a very useful feature that I've described to a number of people over IRC and had them be delighted. Let's add docs for it.

**Comment by mlucy** [comment]
Now that we have changefeeds, `rethinkdb proxy` is extremely useful because it lets us deduplicate changefeed traffic between the actual cluster and the machine hosting the clients.  I think we should probably keep it, and should definitely document it in the meantime.  (If we decide not to keep it, we should make sure we have another way of deduplicating changefeed messages before dropping it.)

@chipotle asked for a brief overview of what `rethinkdb proxy` does.  Basically it adds a node to the cluster that doesn't store any data.  So you can run this node on the same machine as your clients and connect to it over localhost.  This has three main uses:
* It can save intracluster network traffic by routing your query straight to the correct machine.
* It can do some processing itself, lessening CPU load on machines that store data on disk.
* It can deduplicate changefeed messages send to it by other nodes in the cluster.

**Comment by larkost** [comment]
In addition to the points @mlucy mentioned, a `rethinkdb proxy` node is also aware of other nodes that might become unavailable so is the best tool we have to keep a stable connection to the cluster when things go bad.

Personally I see the `poxy` nodes as becoming more and more important as our ability to scale increases.

**Comment by chipotle** [comment]
So: if you have a RethinkDB cluster, you can set up a proxy node on your application server and have the application connect to the proxy rather than to a (non-proxy) machine on the cluster. The proxy will route queries more efficiently, deduplicate changefeed messages and make sure queries don't get sent to unavailable nodes.

If you have more than one application server in this scenario, should each application server run its own proxy, or should there be only one machine running `rethinkdb proxy` in a cluster?

**Comment by larkost** [comment]
I talked to @chipotle in person, and my answer is that in a big setup it would be a good pattern to have a `rethinkdb proxy` process running on each application server. This is especially true the more you use changefeeds.

**Comment by coffeemug** [comment]
> a good pattern to have a `rethinkdb proxy` process running on each application server

:+1: that was the intention when we built it.

**Comment by danielmewes** [comment]
To update on my earlier comments about raft's impact on this: It seems like we will keep the `proxy` mode as it is for 2.1.

**Comment by danielmewes** [comment]
Really like the new documentation for the proxy mode. Very concise. :+1:

**Comment by irony** [comment]
For anyone using docker and rethinkdb, you need to use --bind-all on the proxy to make it accessible from your linked containers.

**Comment by ntquyen** [comment]
@larkost @coffeemug  In a microservice system running containers, in my case is kubernetes. Should I have each microservice use its own `rethinkdb proxy` inside the pod? My concern is that could make hundreds of `rethinkdb proxy`, could that make the rethinkdb cluster performance worse or not at all?

**Comment by danielmewes** [comment]
@ntquyen We haven't really tested anything of that scale. I suspect that there won't be any problems if you stay below 100 proxies or so, but there might be some unexpected slowdowns when getting to a multitude of that.
Also note that proxies are not completely light-weight. While they need less RAM than "proper" RethinkDB servers, and don't need any storage, they will still need a significant amount of RAM for processing queries (depending on which types of queries you're running).

**Comment by jdoliner** [comment]
@ntquyen imo this is a great use case for a daemon controller [0]
That will give you a rethinkdb proxy per node rather than per pod. It should have the same performance characteristics but you won't have to worry about scaling up your controller slowing down the db.

[0] https://github.com/kubernetes/kubernetes/blob/master/docs/admin/daemons.md
