### ISSUE TITLE
Limit 0 should return all records

### ISSUE THREAD

**Issue by dszymczuk** [rethinkdb/docs#1133]
Example (I use rethinkdbdash):

`r.table(tableNotification).orderBy(r.desc('time')).limit(limit)`
is better than:
```
if(limit > 0){
	r.table(tableNotification).orderBy(r.desc('time')).limit(limit).run()
} else {
	r.table(tableNotification).orderBy(r.desc('time')).run()
}
```

**Comment by danielmewes** [comment]
Hi @dszymczuk, thanks for the suggestion.
This is the issue tracker for RethinkDB documentation. Would you mind opening the issue in https://github.com/rethinkdb/rethinkdb/issues ?

Personally I think that this would be a bad idea, because it would feel inconsistent. It makes logical sense that `limit(0)` returns zero rows. It just matches the invariant of `limit` that whichever number you give it, it returns at most that many rows.
It seems to me that you're using `0` as a special value in your code to indicate no limit at all, but this isn't necessarily true in general. Other people might use `-1`, or `null` for example.
I think having `limit(null)` to indicate no limit at all might make sense.

I'm going to close this because it's the wrong issue tracker, but we can carry on at https://github.com/rethinkdb/rethinkdb/issues if you like to.

**Comment by dszymczuk** [comment]
Yes, I'm sorry. I wrote in wrong place. I've written in correct place: https://github.com/rethinkdb/rethinkdb/issues/5807
