### ISSUE TITLE
Explicitly define type hierarchy in Data Types document

### ISSUE THREAD

**Issue by encryptio** [rethinkdb/docs#1141]
We have a type hierarchy in RethinkDB, but it's not documented. Notably, the "DATUM" type which occurs all over our error messages is not explicitly defined anywhere except [in a subsection of the Writing Drivers page](https://rethinkdb.com/docs/writing-drivers/#reql-data), which isn't where most people will look to get a better understanding of ReQL.

Note that it's not a strict hierarchy; `DATUM` and `SEQUENCE` are disparate types, but an `ARRAY` is both.

I might be getting some details wrong (ping @danielmewes and @mlucy for a factual check), but I'm thinking something close to this would be helpful to add to [the data types page](https://rethinkdb.com/docs/data-types/):

---

Note that the examples listed below might not describe all the ways you could get a value of that type.

* `DB`: E.g. the type of `r.db()`.
* `SEQUENCE`: Some sequence of `DATUM`s, possibly infinite, e.g. `r.range()`.
    * `SELECTION`: A set of documents in a table, e.g. the type of `r.table().getAll()`. You can call `r.update()` on these.
        * `TABLE_SLICE`: A contiguous set of documents in a table, e.g. the type of `r.table().between()`.
            * `TABLE`: E.g. the type of `r.table()`.
* `GROUPED_DATA`: E.g. the type of `r.table().group()`.
* `DATUM`: (TODO: what's a good definition here?)
    * `SINGLE_SELECTION`: A single document in a table (or null), e.g. the type of `r.table().get()`. (TODO: should this be below `OBJECT` and `NULL`?)
    * `NULL`: only `null`.
    * `BOOL`: only `true` and `false`.
    * `NUMBER`: Floating point numbers, not including positive or negative infinity or any NaNs.
    * `STRING`: e.g. `"foo"`
    * `ARRAY`: An array of other `DATUM`s, e.g. `[1, null, {"a": "b"}]` (also a `SEQUENCE`; TODO: should we put this type there too?)
    * `OBJECT`: A mapping of `STRING` keys to `DATUM` values, e.g. `{"a": 4, "b": false}`
    * `PTYPE`: Psuedo-types (TODO: definition here?)
        * `BINARY`: e.g. `r.binary("data")`
        * `GEOMETRY`: e.g. `r.point(37.7749,-122.4194)`
        * `TIME`: e.g. `r.time(2013, r.august, 9, 18, 53, 15.012, '-07:00')`
    * `MINVAL` / `MAXVAL`: only `r.minval()` and `r.maxval()` respectively.
* `FUNCTION`: TODO

TODO: Does `STREAM` need to be here? It kinda screws with the whole nearly-hierarchy of the `SEQUENCE` part

**Comment by danielmewes** [comment]
One question is who the audience of this documentation would be. Is this aimed at driver developers who need to understand the type signatures in the ql2.proto file?

Or is this aimed at users who want to program in ReQL? I think as far as those users are concerned, https://rethinkdb.com/docs/data-types/ already has a pretty good description of the relevant data types that is also consistent with the types we are using in the API signatures here I think https://rethinkdb.com/api/ . Though this description doesn't explicitly describe a hierarchy right now (should it?).

**Comment by mlucy** [comment]
A few notes:
* GROUPED_DATA is a pseudotype, at least from an external perspective (we send it over the wire as a pseudotype, internally it's stored differently than the other pseudotypes).
* There's also a `GROUPED_STREAM` type.  (Arguably a stream is a special case of a grouped stream, but it's confusing because grouped streams degrade to grouped data if necessary.)
* `MINVAL` and `MAXVAL` are their own types in the type system.
* I think the `SEQUENCE` chain should be for `STREAM`.  `SEQUENCE` is a word that just means "stream or array", values are never actually of type `SEQUENCE` .
Here's how I would write it:

---

* DB
* STREAM (a kind of **SEQUENCE**)
  * `SELECTION<STREAM>`
    * TABLE_SLICE
      * TABLE
* DATUM
  * NULL
  * BOOL
  * NUMBER
  * STRING
  * ARRAY (a kind of **SEQUENCE**)
    * `SELECTION<ARRAY>`
  * OBJECT
    * `SELECTION<OBJECT>` (formerly SINGLE_SELECTION, can also be NULL)
  * MINVAL
  * MAXVAL
  * PSEUDO_TYPE
    * BINARY
    * GEOMETRY
    * TIME
    * GROUPED_DATA
      * GROUPED_STREAM (this is a little debatable, but it degrades to GROUPED_DATA)
* FUNCTION

**Comment by cjhveal** [comment]
@danielmewes I'm in particular a ReQL user (not driver developer) that was confused by the errors involving `DATUM` and couldn't find it in the documentation. I didn't think to look under the driver development docs. I knew that sometimes those errors could be fixed with a `.coerceTo('ARRAY')` and sometimes with `.coerceTo('DATUM')` but didn't understand what if any the difference was.

**Comment by encryptio** [comment]
This would be aimed at ReQL users who have little to no interest in writing drivers or working on the core, but do want to understand enough of the query execution engine to understand what the type errors they're seeing actually mean, and what "Expected type X but found Y" can be solved by _in general_ (not just in the specific query they're looking at).

I also looked for this kind of documentation when I started experimenting with ReQL, and had to extrapolate `DATUM` myself, and still didn't really understand `SELECTION` and its buddies until I worked on the RethinkDB core myself.

**Comment by danielmewes** [comment]
Good points. I forgot that we're using these terms in error messages.

I think in general ReQL error messages should use type denominators that match the return values of the `.typeOf()` command, which in turn I believe match what we use in the API docs and what we currently describe on https://rethinkdb.com/docs/data-types/ (except for capitalization).
Not that those names differ a bit from what we use in `ql2.proto`. For example we write `SELECTION<OBJECT>` instead of `SINGLE_SELECTION`.

I think most ReQL error messages already follow this schema.

That still leaves some type classes that we use in errors, but don't explain anywhere. `DATUM` is one, and there might be others.

Maybe we should just add descriptions of `DATUM` and potentially other similar "abstract" types to the https://rethinkdb.com/docs/data-types/#rethinkdb-specific-data-types list?

**Comment by cjhveal** [comment]
A couple of point from my perspective as a relatively new user:

- I had seen both `SELECTION<OBJECT>` and `SINGLE_SELECTION` but didn't know they were the same type.
- Adding the "abstract" types to the section you linked would have itched my curiosity. I had guessed that `DATUM` was one of the types listed under [Basic data types](https://rethinkdb.com/docs/data-types/#basic-data-types), but I simply wanted to see it defined somewhere to confirm my suspicions. Now I see I was slightly off.
- This might be a separate issue, but I was pretty confused by why exactly a `SELECTION` was incompatible with `DATUM`. Now I think I understand that I was trying to use a `SELECTION<STREAM>` as an `ARRAY`, which would have to load the entire stream into memory (could still be wrong about that). But neither of those types were directly mentioned in the error, only the more abstract types, which might have obscured the actual issue.

(as an aside, just wanted to say I really appreciate the responsiveness from everyone involved here, raises my already-high regard for what you folks do here and the product you produce).

**Comment by mlucy** [comment]
@danielmewes -- one thing we could think about, actually, would be changing the output of `typeOf` so that `r(1).typeOf()` returns `DATUM<NUMBER>` instead of just `NUMBER`.  That might make the category clearer to people.
