### ISSUE TITLE
update the `bulk insert` answer on our FAQ

### ISSUE THREAD

**Issue by larkost** [rethinkdb/docs#1155]
On our [FAQ page](http://rethinkdb.com/blog/answers-to-common-questions/) we have an answer to "Can RethinkDB do bulk inserts?" that references importing. We should probably link that to our [import](https://rethinkdb.com/docs/importing/) page, as well as mention that we also support importing `json` files.

**Comment by chipotle** [comment]
Ah, this is not the FAQ page, it is the "Answers to Common Questions" page, which is actually a blog entry. So this needs to be re-opened in the `www` repository.

I've been told there is some historical reason why the "FAQ" in the documentation is not actually a list of Frequently Asked Questions but instead is largely about architecture (which is why it's in the architecture TOC section for now), but I really think we should consider moving "Answers to Common Questions" into the FAQ page sometime and make it a FAQ-as-the-term-is-commonly-used page.

**Comment by chipotle** [comment]
Actually, this blog post is from 2012 and begins with a bold italic warning about it all being outdated. I don't think there's a whole lot of value in keeping it updated with new information.
