### ISSUE TITLE
`do` has no examples that chain off of datums

### ISSUE THREAD

**Issue by mglukhovsky** [rethinkdb/docs#135]
We should have an example like:

`r.expr(1).do(function(x) { x.add(1) })`

**Comment by chipotle** [comment]
This ticket predates the current docs for `do`; while there's still no example that chains off a datum like the example above, I don't think we need one. (I'd actually argue that since such an example is pretty far off from the use cases we describe `do` as being good for, it might be counterproductive.)

If someone feels really strongly about this, we can re-open it.
