### ISSUE TITLE
Crystal driver is working. 

### ISSUE THREAD

**Issue by zw963** [rethinkdb/docs#1350]
I just test crystal driver is working, after a quick try, the API almost same as ruby version, except, it not support `#repl` on `r.connect`.

https://github.com/kingsleyh/crystal-rethinkdb

so i consider we should mention it on README, thank you.

**Comment by srh** [comment]
I've accidentally pushed 3be9072e to master instead of making a PR.

So, there it is.

The website now has the Crystal driver.

I haven't put it in the README, as that's supposedly a short list of some of the drivers -- linking to the website for the rest.

https://rethinkdb.com/docs/install-drivers/
