### ISSUE TITLE
Misleading alternative promise implementations on frameworks page

### ISSUE THREAD

**Issue by chrisvariety** [rethinkdb/docs#388]
http://rethinkdb.com/docs/frameworks-and-libraries/

The following JS library descriptions are misleading as the official Javascript driver now supports promises natively:

 - rethinkdb-co (co is actually the library that "Allows using ECMAScript 6 generators", and it can consume promises, so this isn't really necessary)
 - rethinkdbdash ("native promises" is a feature of the official JS driver)
 - RQL Promise (same as above)

Just my opinion, I think RQL Promise is the most egregious, the rest are really subjective.

**Comment by chipotle** [comment]
The RQL Promise library hasn't been listed for a while, I don't think; I'm just going to delete rethinkdb-co, as its last update is from March 2014 (before this ticket was opened!) I'm also going to scan the other libraries to see if they're still being maintained.

**Comment by chipotle** [comment]
While I'm being conservative with what I delete, I took out rethinkdb-co, rdb-cursor-stream, and connect-rethinkdb due to obvious lack of maintenance and incompatibility reports with current RethinkDB versions, and also took out JugglingDB-RethinkDB due to the warnings in its README file which include, literally, "JugglingDB is awfully maintained and I suggest you use another ORM."
