### ISSUE TITLE
Datacenters still mentioned in `tableCreate` on the API index

### ISSUE THREAD

**Issue by mglukhovsky** [rethinkdb/docs#634]
From http://rethinkdb.com/api/javascript/#table_create:

> tableCreate
> ...
> - `datacenter`: the name of the datacenter this table should be assigned to.

There may be other mentions of datacenters on the index.

**Comment by chipotle** [comment]
Actually, the `tableCreate` index entry is just wrong. I've been using a style of just including the first paragraph of a command description in the index along with a quick example, and leaving the options on the command's detail page you get to with "read more"; I didn't notice this one still had the whole bullet point list of options in the index I'd be inclined to just remove everything between "...a collection of JSON documents" and the example.

There aren't any other mentions of datacenters on the index, but the phrase occurs in a few other places: architecture, both comparison documents, and the intro to ReQL page. It's talking about them in the abstract rather than the now-gone `datacenter` option, but it's possible some of them should be rephrased.
