### ISSUE TITLE
Reorganize config file and cluster docs

### ISSUE THREAD

**Issue by chipotle** [rethinkdb/docs#643]
A few nits in the current version:

* `machine-name` is now `server-name`
* We don't describe how to do server tags in config files
* We don't explicitly describe the format and show an example (we have a `default.conf.sample`, but this should be discussed more prominently)
* It may not be clear that every CLI option is available in a config file (that's true, right?)

I'm still not sure whether this should be broken out into a separate "config file" doc page, but I'm leaning toward doing so; it would let us talk about the config file format in a bit more detail and simplify the "Create a cluster on system startup" document. Any thoughts?

**Comment by danielmewes** [comment]
> It may not be clear that every CLI option is available in a config file (that's true, right?)

Most definitely are. @AtnNn probably knows whether all of them are.

**Comment by danielmewes** [comment]
I think breaking it out makes sense. I've always found it a bit odd that the configuration options were described as part of the "Create a cluster on system startup" page.

(Another thing is that the "Create a cluster on startup" title is a bit odd, because it also applies if I only want to start a single server. Also we don't really "create" the cluster on startup, we just start it. I think you had already addressed that in your proposal for an improved documentation structure though.)

**Comment by suparngp** [comment]
On the configuration options doc page, it is mentioned that the server_tag can be described in the config file. However, this is not the case anymore.

**Comment by danielmewes** [comment]
@suparngp That should still be working. Is it not working for you?
