### ISSUE TITLE
Better document {default: r.error} for `filter`

### ISSUE THREAD

**Issue by mglukhovsky** [rethinkdb/docs#644]
The [docs for filter](http://rethinkdb.com/api/javascript/filter/) currently state in the intro paragraph:

> The filter command wraps predicates in an implicit .default(false), so if the predicate tries to access a field that doesn't exist in a given document, that document is not returned. The default optional argument sets the value returned for missing fields, rather than false. Setting it to r.error() will throw an RqlRuntimeError when a non-existent field is accessed.

This is accurate, but unfriendly language. Adding a quick example, improving the readability of the paragraph, and working to explain that `filter` can operate in two modes: skipping `undefined` values, or throwing them would help users who are confused when `filter` doesn't behave like they would expect for complex cases.

**Comment by danielmewes** [comment]
(Note that we don't currently have a notion of an `undefined` value. This is being discussed in https://github.com/rethinkdb/rethinkdb/issues/1721 but doesn't currently exist.)

**Comment by mglukhovsky** [comment]
Thanks for clarifying, @danielmewes.

**Comment by chipotle** [comment]
I'm expanding the description of the `default` optarg considerably and dropping the link to the `default()` command, because even if that's what it's using internally it doesn't have quite the same effect in practice: you can set it to a value other than `true`, `false` and `r.error()` but it doesn't seem like doing so is actually useful. (One might argue that the optarg might have been better named `skip`, but it's probably too late to do that.)

As for examples, though, I don't think we're really short on those -- `filter` just went through a fairly major reorganization and there's a whole section titled "handling missing fields."
