### ISSUE TITLE
Improve the abbreviated documentation for `r.do`

### ISSUE THREAD

**Issue by mglukhovsky** [rethinkdb/docs#701]
`do` has the current (correct but confusing) [abbreviated description](http://rethinkdb.com/api/python/#do):

> Evaluate an expression and pass its values as arguments to a function or to an expression.

As @coffeemug said, it's really just "like `map`, but for one thing."]

As @segphault said, "it lets you call an anonymous function on one or more values."

**Comment by coffeemug** [comment]
We should also have a short description for when you might want to use such a thing.

**Comment by deontologician** [comment]
related: #620

**Comment by chipotle** [comment]
I think you need to capture the notion of "evaluate an expression" to explain what `do` is for -- you're applying a function to one more values returned from ReQL queries.

Perhaps as a draft: "Call an anonymous function using return values from other ReQL commands or queries as arguments."

**Comment by coffeemug** [comment]
>  Call an anonymous function using return values from other ReQL commands or queries as arguments.

That makes a lot of sense. I'd also focus on good examples because with `do` a description can only go so far. When would I need to call an anonymous function using the values of other ReQL commands? I think examples will make or break this doc entry.

**Comment by mlucy** [comment]
Here's one classic example: `r.table('people').get('bob').do{|bob| bob['hourly_salary'] * bob['hours_worked']}`.

**Comment by chipotle** [comment]
Well, we have two examples already, including one sort of like that:

```rb
r.table('players').get('f19b5f16-ef14-468f-bd48-e194761df255').do { |player|
    player['gross_score'] - player['course_handicap']
}.run(conn)
```

I'm not entirely sure what to in the context of #620 -- the examples we have involve using the results of queries in the function and doing branching. Maybe there's a more complex example that we could come up with, but there's only one example using `do` in the cookbook I could find and while the *overall* example is complex, the function being passed to `do` is still fairly straightforward.

**Comment by deontologician** [comment]
I think we should make it clear there are 3 major reasons to use do, and give an example for each:

 - to re-use results
 - to ensure ordering (do this operation, then when that's complete do this operation)
 - to "map over one document"

The third is probably just going to catch people googling, and could explain why usually you can just chain operations, and only need to use .do if you have to use the result more than once.

**Comment by mglukhovsky** [comment]
"to map over one document" should be the leading example, in my opinion. It
makes `r.do` much more accessible once you understand that.

**Comment by chipotle** [comment]
I'm having trouble transmogrifying these into concrete examples. To wit, I'm not sure when would you ever use `do` when you *didn't* need to reuse the result of the query being passed in.

Here's the first of the two existing examples, for instance:

```py
r.table('players').get('86be93eb-a112-48f5-a829-15b2cb49de1d').do(
    lambda player: player['gross_score'] - player['course_handicap']
).run(conn)
```

This doesn't use the specific phrase "map over one document," but that's what it's doing. However, the reason this is in `do` is because you need to use `player` twice, right? If that query above had a fixed course handicap, you wouldn't need `do` at all:

```py
r.table('players').get('86be93eb-a112-48f5-a829-15b2cb49de1d'
    )['gross_score'].sub(5).run(conn)
```

Are there any use cases for "mapping over one document" *without* reusing results? I've been combing documentation, examples, and blog posts, and haven't found one yet.

Is it possible that the best way to describe *all* the use cases of `do` is that it's for managing variable scope? Yes, it's a single-element map, but what you're actually using it for is the ReQL equivalent of Python's `with...as` construct.

**Comment by deontologician** [comment]
If you need to do one thing after another, you would want to use do to do sequencing:

```python
r.table("foo").insert({'id': 3}).do(lambda result: r.branch(result['inserted'] != 0, r.some_subexpr, r.error)
```

This is probably much less often needed than using `.do` to reuse results, but it's something you can't quite do without it.

My understanding is the same as your as far as "map over one document". Only use do if you need to reuse the result, otherwise you can just chain more terms. But I was thinking someone new to ReQL might google for mapping over one document, and it would be useful to have them land here.
