### ISSUE TITLE
div query

### ISSUE THREAD

**Issue by istiakk** [rethinkdb/docs#739]
why i can not perform this query

r.object(
    "total_page_loads",
    r.table("test_db")("page_loads").sum(),
  "total_clicks",
    r.table("test_db")("clicks").sum(),
  'aggre',
  r.expr('total_page_loads').div('total_clicks')
)

**Comment by danielmewes** [comment]
@istiakk is this an example from the documentation?

The problem is probably with this line:
```
r.expr('total_page_loads').div('total_clicks')
```

You're trying to divide two strings there. I assume this might be what you want:
```js
r.object(
  "total_page_loads",
  r.table("test_db")("page_loads").sum(),
  "total_clicks",
  r.table("test_db")("clicks").sum(),
).merge({
  aggre: r.row('total_page_loads').div(r.row('total_clicks'))
})
```

or even simpler without `r.object`:
```
r.expr({
  "total_page_loads": r.table("test_db")("page_loads").sum(),
  "total_clicks": r.table("test_db")("clicks").sum()
}).merge({
  aggre: r.row('total_page_loads').div(r.row('total_clicks'))
})
```

Note that we have do compute `total_page_loads` and `total_clicks` first before we can refer to them in the next term.

**Comment by danielmewes** [comment]
I assume this was a question unrelated to our documentation.
@istiakk Please let me know if this was actually a bug in our documentation.
