### ISSUE TITLE
Changefeeds "Scaling considerations" section has the wrong link

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/docs#743]
Currently the section points the user at http://rethinkdb.com/docs/publish-subscribe/javascript/ and it should instead be pointing at http://rethinkdb.com/docs/rabbitmq/javascript/ . Basically, the section indicates you can get more scalability by using publish subscribe, but the linked article only describes an alternate interface to changefeeds, it doesn't add scalability. The rabbitmq article (in principle) could provide more scalability since it is a dedicated message queue.

This also raises the question of whether "changefeeds don't scale well" is still accurate, or whether they scale worse than having a message queue would. Both are going to require more memory as more unconsumed changes are sitting around in buffers. @mglukhovsky @danielmewes any thoughts on this? I think @VeXocide did tests with thousands of changefeeds. The current copy seems to indicate changefeeds will devour your memory if you have more than a few.

**Comment by deontologician** [comment]
This came up in the discussion of rethinkdb/example-pubsub#5

**Comment by mglukhovsky** [comment]
I think the current language is too conservative, regarding scalability. @danielmewes, would you agree?

**Comment by danielmewes** [comment]
I agree, we should rewrite that section.

I don't think the limitations mentioned in there apply anymore.
We could remove the section altogether, but some users are concerned about changefeed scalability (the question has come up multiple times). So I think we should replace it by something that explains how well changefeeds scale in general, rather than only pointing out limitations.

@mlucy I believe you once wrote a summary of changefeed scalability. Maybe it was for a question on HackerNews or on the mailing list? Do you still have that summary around by any chance?

I think we should still refer to RabbitMQ somewhere else in the article for cases where users need better guarantees (like "at least once" delivery).

**Comment by mlucy** [comment]
I can't seem to find it.  Roughly, the number of intracluster messages is proportional to the number of servers with at least one open changefeed connection times the number of writes.  It would be nice to have some actual performance numbers, though.

**Comment by chipotle** [comment]
I'd like a little bit to put here in place of the current paragraph, which reads:

> Available memory affects changefeed performance, and running multiple changefeeds on the same database may scale linearly at worst case. If you have an application with dozens (or hundreds or thousands) of clients that need real-time updating, rather than creating a changefeed for each client consider using a publish-subscribe model that distributes to the clients through a message exchange.

It sounds like the whole part about "scale linearly at worst case" isn't true, but if there are any concerns people should know about this would be the place to mention them. I can change the part about publis-subscribe to say something like "If you need real-time updating for many clients with guaranteed delivery, consider using..." Although that raises the question of what we do and don't guarantee with changefeeds and why (e.g., RabbitMQ offers scenarios where delivery acknowledgement is required and changefeeds don't).
