### ISSUE TITLE
Changes: Type signature incomplete

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/docs#759]
Here we only list http://rethinkdb.com/api/javascript/changes/ `table` and `singleSelection` as possible left-hand side arguments to `changes`.

This is no longer adequate, since `changes` can also be called on `selection`s and on some `stream`s.

I think the two types that we have to list are `stream.changes` and `singleSelection.changes`.

@Slava noticed this because `changes` didn't show up as a suggestion in the Data Explorer after certain operations (https://github.com/rethinkdb/rethinkdb/issues/4214).

**Comment by stuartpb** [comment]
I think the docs need to explain what kind of streams `changes` works on. Also, I think the body of the text needs some updates:

```
// Note that this will have to look at and discard all the changes to
// rows besides Bob's.  This is currently no way to filter with an index
// on changefeeds.
r.table('test').changes().filter(r.row('new_val')('name').eq('Bob')).run(conn, callback)
```

**Comment by chipotle** [comment]
The "[Changefeeds in RethinkDB](http://rethinkdb.com/docs/changefeeds/ruby/)" article lists the commands you can append `changes` to. That might be what you're looking for?

I'll check on that comment, but i'm pretty sure you're right -- we should go through all the examples for `changes`, because they were written for the first version of changefeeds and there's probably a few others which show more convoluted examples than we need now. I'll open a new issue about that.
