### ISSUE TITLE
Update FAQ for auto failover

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/docs#773]
http://www.rethinkdb.com/docs/architecture/#availability-and-failover has a section on "Availability and Failover" which needs to be updated for RethinkDB 2.1.

**Comment by timmaxw** [comment]
In addition to the "Availability and failover" section being out of date, there are some smaller things that need to be updated:
* In the event of a netsplit, what matters is which side of the netsplit has a majority of voters, not which side has the primary replica.
* RethinkDB now uses the Raft protocol instead of semilattices to store and propagate cluster configuration in most cases, but we still use semilattices in a few situations. When we do use semilattices, we use timestamps rather than vector clocks.

**Comment by timmaxw** [comment]
The https://github.com/rethinkdb/docs/blob/v2.1/0-about-rethinkdb/faq.md refers to `useOutdated` and "the upcoming release of RethinkDB (2.1)". These should be updated.

**Comment by timmaxw** [comment]
https://github.com/rethinkdb/docs/blob/v2.1/0-about-rethinkdb/limitations.md also refers to "the upcoming release of RethinkDB (2.1)".

**Comment by timmaxw** [comment]
https://github.com/rethinkdb/docs/blob/v2.1/0-about-rethinkdb/technical-comparison-tables.md should mention that we now support fully automatic failover too.
