### ISSUE TITLE
The emergencyRepair flag is missing in command syntax

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/docs#820]
http://docs.rethinkdb.com/2.1/api/javascript/reconfigure/
`emergencyRepair` is listed in the description, but doesn't appear in the command syntax. Maybe it should be an additional line since it doesn't work in combination with the other arguments?

On a different note: Below "Specify emergencyRepair with one of two string options:", should the values `unsafe_rollback` and `unsafe_rollback_or_erase` be written as strings (i.e. `"unsafe_rollback"`) maybe to make it more obvious that they are string values (I'm not sure how we do that elsewhere)?

**Comment by chipotle** [comment]
I left that out of the command syntax on purpose because it was so unusual, but adding it as an additional line is a good idea, so I'll do that.

The quotes were removed in review, because they seemed unnecessary in this instance. I don't think we generally show string options with "quotes" unless the option takes mixed values (if it can be something like `true`, `false` and `"self-destruct"`).

**Comment by danielmewes** [comment]
Got it. I think the extra line would be nice.
