### ISSUE TITLE
Document Python driver Twisted backend

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/docs#831]
The RethinkDB 2.1 Python driver will come with support for Twisted in addition to Tornado.
https://github.com/rethinkdb/rethinkdb/pull/4096

Hence http://rethinkdb.com/api/python/set_loop_type/ and http://rethinkdb.com/docs/async-connections/ need to be expanded.

I don't actually know how the Twisted syntax works. @Tryneus would you mind writing up some code examples similar to the ones in http://rethinkdb.com/docs/async-connections/#python-and-tornado ?

**Comment by chipotle** [comment]
I'm going to need a quick writeup similar to the Tornado stuff to be able to get going on these…

**Comment by chipotle** [comment]
Pinging @Tryneus on this again.

**Comment by Tryneus** [comment]
I used the existing Tornado examples as a starting point.  I skipped the sections on running tasks in the background and canceling background tasks because these are just generic Tornado/Twisted usage, and we probably shouldn't be telling users how to do this.  In addition, the Tornado section seems to end quite abruptly, so I added a bit more after the final example.

### Basic Usage
The `set_loop_type` command should be used before `connect` to set the RethinkDB Python driver to use asynchronous event loops.  This should be set to `'twisted'` to use a `Connection` compatible with the Twisted reactor.
 
```py
import rethinkdb as r
from twisted.internet import reactor, defer
from twisted.internet.defer import inlineCallbacks, returnValue

r.set_loop_type('twisted')
connection = r.connect(host='localhost', port=28015)
```

After executing `set_loop_type`, `r.connect` will return a Tornado `Deferred`, as will `r.run`.

**Example:** Simple use

```py
@inlineCallbacks
def single_row(conn_deferred):
    # Wait for the connection to be ready
    conn = yield conn_deferred
    # Insert some data
    yield r.table('test').insert([{"id": 0}, {"id": 1}, {"id": 2}]).run(conn)
    # Print the first row in the table
    row = yield r.table('test').get(0).run(conn)
    print(row)

# Output
{u'id': 0}
```

**Example:** Using a cursor

```py
@inlineCallbacks
def use_cursor(conn):
    # Insert some data
    yield r.table('test').insert([{"id": 0}, {"id": 1}, {"id": 2}]).run(conn)
    # Print every row in the table.
    cursor = yield r.table('test').order_by(index="id").run(conn)
    while (yield cursor.fetch_next()):
        item = yield cursor.next()
        print(item)

# Output:
{u'id': 0}
{u'id': 1}
{u'id': 2}
```

Note that looping over a cursor must be done with `while` and `fetch_next`, rather than using a `for x in cursor` loop.

### Error handling

If an error occurs during an asynchronous operation, the `yield` statement will throw an exception as normal. This may happen immediately (for example, you might reference a table that doesn’t exist), but your application might receive large amounts of data before the error (for example, your network might be disrupted after the connection is established).

One error in particular is notable. If you have a task that consume a changefeed indefinitely, and the connection closes, the task will experience a `ReqlRuntimeError`.

**Example:** Re-thrown errors

```py
@inlineCallbacks
def bad_table(conn):
    yield r.table('non_existent').run(conn)

Unhandled error in Deferred:
Traceback (most recent call last):
Failure: rethinkdb.errors.ReqlOpFailedError: Table `test.non_existent` does not exist in:
r.table('non_existent')
^^^^^^^^^^^^^^^^^^^^^^^

```

**Example:** Catching runtime errors

```py
@inlineCallbacks
def catch_bad_table(conn):
    try:
        yield r.table('non_existent').run(conn)
    except r.ReqlRuntimeError:
        print("Saw error")

# Output
Saw error
```

### Subscribing to changefeeds

The asynchronous database API allows you to handle multiple changefeeds simultaneously by running multiple background tasks.  As an example, consider this changefeed handler:

```py
@inlineCallbacks
def print_feed(conn, table):
    feed = yield r.table(table).changes().run(conn)
    while (yield feed.fetch_next()):
        item = yield feed.next()
        print("Seen on table %s: %s" % (table, str(item)))
```

We can schedule it on the Twisted `reactor` with this code:
```py
reactor.callLater(0, print_cfeed_data, conn, table)
```

Now the task will run in the background, printing out changes.  When we alter the table, the changes will be noticed.

Now consider a larger example:

```py
@inlineCallbacks
def print_feed(conn, table, ready, cancel):
    def errback_feed(feed, err):
        feed.close()
        return err

    feed = yield r.table(table).changes().run(conn)
    cancel.addErrback(lambda err: errback_feed(feed, err))
    ready.callback(None)
    while (yield feed.fetch_next()):
        item = yield feed.next()
        print("Seen on table %s: %s" % (table, str(item)))

@inlineCallbacks
def table_write(conn, table):
    for i in range(10):
        yield r.table(table).insert({'id': i}).run(conn)

@inlineCallbacks
def notice_changes(conn, *tables):
    # Reset the state of the tables on the server
    if len(tables) > 0:
        table_list = yield r.table_list().run(conn)
        yield defer.DeferredList([r.table_drop(t).run(conn) for t in tables if t in table_list])
    yield defer.DeferredList([r.table_create(t).run(conn) for t in tables])

    readies = [defer.Deferred() for t in tables]
    cancel = defer.Deferred()
    feeds = [print_feed(conn, table, ready, cancel) for table, ready in zip(tables, readies)]

    # Wait for the feeds to become ready
    yield defer.gatherResults(readies)
    yield defer.gatherResults([table_write(conn, table) for table in tables])

    # Cancel the feeds and wait for them to exit
    cancel.addErrback(lambda err: None)
    cancel.cancel()
    yield defer.DeferredList(feeds)

yield notice_changes(conn, 'a', 'b')

# Output
Seen on table b: {u'old_val': None, u'new_val': {u'id': 0}}
Seen on table a: {u'old_val': None, u'new_val': {u'id': 0}}
Seen on table b: {u'old_val': None, u'new_val': {u'id': 1}}
Seen on table a: {u'old_val': None, u'new_val': {u'id': 1}}
Seen on table b: {u'old_val': None, u'new_val': {u'id': 2}}
Seen on table a: {u'old_val': None, u'new_val': {u'id': 2}}
Seen on table b: {u'old_val': None, u'new_val': {u'id': 3}}
Seen on table a: {u'old_val': None, u'new_val': {u'id': 3}}
Seen on table b: {u'old_val': None, u'new_val': {u'id': 4}}
Seen on table a: {u'old_val': None, u'new_val': {u'id': 4}}
Seen on table b: {u'old_val': None, u'new_val': {u'id': 5}}
Seen on table a: {u'old_val': None, u'new_val': {u'id': 5}}
Seen on table b: {u'old_val': None, u'new_val': {u'id': 6}}
Seen on table a: {u'old_val': None, u'new_val': {u'id': 6}}
Seen on table b: {u'old_val': None, u'new_val': {u'id': 7}}
Seen on table a: {u'old_val': None, u'new_val': {u'id': 7}}
Seen on table b: {u'old_val': None, u'new_val': {u'id': 8}}
Seen on table a: {u'old_val': None, u'new_val': {u'id': 8}}
Seen on table a: {u'old_val': None, u'new_val': {u'id': 9}}
Seen on table b: {u'old_val': None, u'new_val': {u'id': 9}}
```

Here, we can listen for changes on multiple tables at once.  We simultaneously write into the tables, and observe our writes appear in the changefeeds.  We then cancel the changefeeds after we've written 10 items into each of the tables.

**Comment by chipotle** [comment]
Do you think it'd be a good idea to remove the "running a coroutine in the background" examples from the Tornado documentation, and leave the "larger example" of changefeeds as sufficient?

**Comment by Tryneus** [comment]
@chipotle - yes, while reading the Tornado docs to prepare this, I was very confused as to why we were going over that.  If someone wants to learn how to run Twisted/Tornado tasks in the background and cancel them correctly, there are plenty of generic tutorials out there.  That section doesn't even mention ReQL.
