### ISSUE TITLE
Can I write doc for tutorial?

### ISSUE THREAD

**Issue by kureikain** [rethinkdb/docs#893]
I write a simple website monitoring with RethinkDB changfeed https://github.com/kureikain/simplyrethink/tree/master/example/server_monitoring
I wonder if I can submit a tutorial for it? Or the tutorials are only written by RethinkDB dev

**Comment by danielmewes** [comment]
Hi @kureikain, are you talking about the example projects in our docs? http://rethinkdb.com/docs/examples/

In general we're very happy about pull requests.

Keep in mind that depending on the contents, it might take a few iterations before we can merge a new docs page. So you might want to publish your tutorial independently somewhere while we're reviewing it and working with you on getting it into the right format etc.

(closing because it's more of a question than an issue)
