### ISSUE TITLE
Document include_initial functionality

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/docs#920]
The new `include_initial` option in RethinkDB 2.2 allows creating an "atomic changefeed" on a query.

Consider a query such as `r.table('test')`.
When a changefeed is created with
`r.table('test').changes({includeInitial: true})`,
the current contents of the table are streamed over the cursor. The initial results will have a `new_val` field, but no `old_val`.

The initial results can be intermixed with changes, as long as an initial result for the given document has been sent before. For example the initial value for the document `{id: "a", val: 0}` can be sent first, followed by a change `{old_val: {id: "a", val: 0}, new_val: {id: "a", val: 1}}` followed by another initial result for a different document `{id: "b", val: 0}`.

Eventually a document `{state: "ready"}` will be seen. After that point, all subsequent results on the cursor will be change documents, and one can be sure that the full set of results from the query at that point in time has been transmitted. (@mlucy: Is the state document always sent or only when combined with `include_states`?)

`include_initial` works for most if not all of the queries that currently support changefeeds (@mlucy are there any exceptions?).

The corresponding issue on the server: https://github.com/rethinkdb/rethinkdb/issues/3579

@mlucy Is my description correct? Anything that you think is worth adding?

**Comment by mlucy** [comment]
> The initial results will have a `new_val` field, but no `old_val`.

We also now have a concept of an "uninitial" result, which is a result with an `old_val` field but no `new_val`.  You get one of these when a document moves from a part of the range that has already been read by the initializer to a part of the range that hasn't.  It's different from a `delete` (represented by a `null` `new_val` field), but can be treated the same by clients that are just trying to maintain a running view of the data.  (It's different from a `delete` because `deletes` are often scarier.  For example, if you're getting changes on `table.between(0, 100, index: 'idx')`, a `delete` indicates that a document was either removed from the table or left the range `[0, 100)`, while an `uninitial_val` indicates that a document's index value changed to a part of the `[0, 100]` range we haven't read yet but is still in the range.)

> Is the state document always sent or only when combined with `include_states`?

Only when `include_states` is set.

> `include_initial` works for most if not all of the queries that currently support changefeeds (@mlucy are there any exceptions?).

I don't think there should be.

---

Some things worth adding:

* We're changing the default behavior of `.get.changes` and `.order_by.limit.changes`.  They used to return initial values by default, and now they don't (you have to set the optarg).

* We've added an `on_uninitial_val` handler to the Ruby EventMachine interface that works similarly to `on_initial_val`.

**Comment by coffeemug** [comment]
> We also now have a concept of an "uninitial" result, which is a result with an `old_val` field but no `new_val`.

Mucking about with `old_val` and `new_val` to indicate different states to the user is proving to be surprisingly versatile and elegant. If RethinkDB were written in Haskell, we could have published at least three papers about this.

**Comment by chipotle** [comment]
Closed in 4ba7917af9f7c0a9494551680aaadea780af1bdf
