### ISSUE TITLE
Add reference to Swift driver

### ISSUE THREAD

**Issue by pixelspark** [rethinkdb/docs#924]
Please add a reference to the Swift (native) driver (currently in development, but mostly functional): https://github.com/pixelspark/rethink-swift.

**Comment by pixelspark** [comment]
Hi, this still on your radar?

Perhaps you should also link to [Warp](http://warp.one), an OS X database tool that allows for easy data import and export to and from RethinkDB. Written in Swift, uses the RethinkDB Swift driver!

**Comment by chipotle** [comment]
It is on the radar, sorry! After the holidays I'll get back to add both of these.

**Comment by chipotle** [comment]
This isn't considered production-ready yet, according to its readme file -- is it a good idea to add it to the page yet? I can't tell offhand how much ReQL it supports, but I think it needs to be reasonably feature complete for us to list it.

**Comment by pixelspark** [comment]
I wouldn't recommend using the driver for your bank account back-end just yet, however it is fairly stable. It also implements most of the ReQL commands and as you can see from the commit log, implementing the remaining ones should take too much work (in terms of lines of code). 

This is a bit of a chicken-and-egg situation - adding the driver to the docs should help some people out and at the same time increase the level of real-world testing. I'd suggest adding it somewhere as a community-developed, experimental driver. Your call though.

**Comment by pixelspark** [comment]
By the way, [this file](https://github.com/pixelspark/rethink-swift/blob/master/Rethink/Rethink.swift) lists all ReQL terms that are currently supported.

**Comment by danielmewes** [comment]
It does look reasonably complete to me. I noticed that geospatial terms are missing, and (possibly more importantly) `group`. That puts it a bit on the edge, but I think it's fine for being listed. Some of the other listed drivers aren't complete either.

One last question though @pixelspark : Can you pass optional arguments to terms such as `between`, `distinct` etc? I couldn't tell from a quick look at the code.

**Comment by pixelspark** [comment]
@danielmewes geospatial commands and optional arguments are indeed missing right now. I think  those can be added fairly easily.

**Comment by danielmewes** [comment]
Hmm missing optargs are a pretty significant limitation, because they make it impossible to use any secondary indexes for example (unless your driver already supports optargs in that particular case?).
I think the other limitations are ok, but (at least the basic) optional argument should be supported for inclusion in the drivers list.

@chipotle What do you think about changing the "Older community-supported drivers" section into a "Community-supported drivers with limited features" section?
We should also remove many drivers that are currently in there, because they are still based on protocol buffers and we don't support those anymore at all. Namely these would be the two Java drivers and the C driver. The other ones appear to be using the JSON protocol, and would fit into the "limited feature drivers" section.

**Comment by chipotle** [comment]
That sounds like a good idea.

**Comment by danielmewes** [comment]
Ok let's do that then. :+1:

**Comment by pixelspark** [comment]
@danielmewes I will look into supporting optargs as soon as I can find the time!

**Comment by danielmewes** [comment]
@pixelspark Awesome, thanks for your work on the driver!

We'll put it in the new special list on the drivers download page for now. Once it has optional arguments, I think we can move it up into the main list.

**Comment by pixelspark** [comment]
@danielmewes most of the optargs have now been implemented, as well as the more exotic operations. Additionally we support the new SCRAM-based authentication (i.e. the V1_0 protocol).

**Comment by danielmewes** [comment]
Awesome, thanks for the update @pixelspark .

@chipotle could you move the Swift driver to the main drivers list please?
