### ISSUE TITLE
Clarify Secondary Index Write Consistency on Insert,Update,Delete

### ISSUE THREAD

**Issue by bchavez** [rethinkdb/docs#988]
Hello,

I couldn't find any information in the documentation regarding the following question:

> Is there a way to ensure that an `insert()` will only return when all necessary properties have been indexed? Something like `.insert(...).sync()`, but I want to ensure that sync will only return when the document has been persisted and ​*indexed*​.

@ha1331 helped and mentioned document inserts are atomic and conclude with secondary indexes appropriately updated and indexes wont ever lag behind inserts. Also confirmed this from a SO @coffeemug post here: http://stackoverflow.com/a/18195786/9275

The question came up because some other DB systems can use index methods that lag behind table writes. 

The documentation for `insert`, `udpate`, `delete`, `sync` should mention something about secondary index consistency (and possibly secondary index consistency in replicas too). From what I've found in the SO post, secondary Indexes are instantly updated on the conclusion of a table `insert/update/delete` when `durability=hard` on the primary node.

Thanks,
Brian

**Comment by danielmewes** [comment]
Hi @bchavez , thanks for bringing that up.

In general RethinkDB doesn't make any difference between (secondary) indexes and the data itself when it comes to consistency semantics. The guarantees are exactly the same for all indexes, including the primary and all secondary indexes.

My suggestion would be to add a note to the document on secondary indexes http://rethinkdb.com/docs/secondary-indexes/javascript/ , rather than to the API docs of each write term.
The consistency guarantees are independent of the particular write term used.
